# Generated by Django 2.1.5 on 2019-10-04 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registeruser', '0002_auto_20190830_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(help_text='digits only, no brackets or dashes', max_length=15),
        ),
    ]
