# Generated by Django 2.1.5 on 2019-08-21 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CampPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_in_days', models.IntegerField()),
                ('price_in_dollars', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CampTheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=200)),
                ('field_trip', models.CharField(max_length=200)),
                ('summary', models.TextField()),
            ],
            options={
                'ordering': ['week_date'],
            },
        ),
        migrations.CreateModel(
            name='CampWeek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_num', models.IntegerField()),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
            ],
            options={
                'ordering': ['week_num'],
            },
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('dob', models.DateField(max_length=12)),
                ('grade_in_fall', models.CharField(default='K', max_length=1)),
                ('camps', models.ManyToManyField(blank=True, related_name='camper', to='camplist.CampTheme')),
            ],
            options={
                'verbose_name_plural': 'children',
            },
        ),
    ]
