# Generated by Django 2.1.5 on 2019-08-21 20:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('camplist', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', related_query_name='parent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='camptheme',
            name='price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camplist.CampPrice'),
        ),
        migrations.AddField(
            model_name='camptheme',
            name='week_date',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='camplist.CampWeek', verbose_name='Week number and start date/end date'),
        ),
    ]
