# Generated by Django 2.1.5 on 2019-08-23 22:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('camplist', '0003_auto_20190823_0344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', related_query_name='parent', to=settings.AUTH_USER_MODEL),
        ),
    ]
